apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  namespace: devops
spec:
  type: LoadBalancer
  selector:
    app: flaskapp
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 5000
